#!/bin/bash

###############################################################################
#
# IMPORTANT:
# This script assumes that if yay is installed, pacman is also installed!
#
###############################################################################


# Define array of all package managers
all_pms=(apt yum dnf pacman yay brew port snap flatpack)

# Let the user know which package managers are listed.
echo This script intends to support the following package managers:
echo ${all_pms[*]}
echo

# Declare array to hold package managers installed on this system
declare -a these_pms
# Set a variable telling us if yay is installed (for use in the case switch)
haveyay=false
# Fill array of package managers installed on this system
# NOTE: The presence of yay will be held in $haveyay, not in $these_pms.
for i in "${all_pms[@]}"
do
  if which $i &> /dev/null
  then
    #these_pms+=($i)
    if [ $i = yay ]
    then
      haveyay=true
    else
      these_pms+=($i)
    fi
  fi
done

# Run a full system upgrade using all installed package managers
###############################################################################
# TODO:
# ALTERNATIVELY: If there is more than one package manager installed, allow the
# user to choose which one(s) to use.
###############################################################################
for i in "${these_pms[@]}"
do
  case $i in
    apt)
      echo /---------------------------\\
      echo \| Found apt
      echo \|
      echo \| Updating apt repositories
      echo \\---------------------------/
      sudo apt update
      echo /------------------------\\
      echo \| Upgrading apt packages
      echo \\------------------------/
      sudo apt full-upgrade
      echo /-----------------------------------\\
      echo \| Removing unnecessary apt packages
      echo \\-----------------------------------/
      sudo apt autoremove
      echo /-----------------------\\
      echo \| Finished updating apt
      echo \\-----------------------/
      ;;
    pacman) # If yay installed, it is used instead of pacman
      if [[ $haveyay=true ]];
      then
        echo /-------------------------------------------------\\
        echo \| Found pacman, but yay is also installed.
        echo \| Using yay...
        echo \|
        echo \| Upgrading all packages including those from AUR
        echo \\-------------------------------------------------/
        yay -Syyu
        echo /-----------------------\\
        echo \| Finished updating yay
        echo \\-----------------------/
      else
        echo /------------------------\\
        echo \| Found pacman
        echo \|
        echo \| Upgrading all packages
        echo \\------------------------/
        pacman -Syyu
        echo /--------------------------\\
        echo \| Finished updating pacman
        echo \---------------------------/
      fi
      ;;
    brew)
      echo /----------------------------------\\
      echo \| Found brew
      echo \|
      echo \| Updating brew formulae and casks
      echo \\----------------------------------/
      brew update
      echo /------------------------------\\
      echo \| Upgrading formulae and casks
      echo \\------------------------------/
      brew upgrade
      echo /--------------------------------------------\\
      echo \| Finished upgrading brew formulae and casks
      echo \|
      echo \| To make sure that your whole system is up
      echo \| to date, open App Store and update any
      echo \| software installed from Apple\'s repos.
      echo \\--------------------------------------------/
      ;;
    snap)
      echo /------------------------\\
      echo \| Found snap
      echo \|
      echo \| Updating snap packages
      echo \\------------------------/
      snap refresh --color=auto
      echo /---------------------------------\\
      echo \| Finished updating snap packages
      echo \\---------------------------------/
      ;;
    *)
      echo Found $i, but it is not yet supported by this script.
      ;;
  esac
done
